[package]
name = "messages"
version = "0.1.0"
authors = ["Vladimir Komendantskiy <komendantsky@gmail.com>"]

[dependencies]
error-chain = "0.11.0"
log = "0.4.1"
simple_logger = "0.5"
protobuf = "1.4.4"

[build-dependencies]
protoc-rust = "1.4.4"
